#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

chown -R www-data:www-data config/docker
# If config/config.json is not (!) not (||) empty, remove config/INSTALLING
test ! -s config/config.json || (rm -f config/INSTALLING && echo "INSTALLING removed")

exec "$@"
